-- Script Date: 22/06/2017 12:44  - ErikEJ.SqlCeScripting version 3.5.2.64
DROP TABLE IF EXISTS [TrackPerformers];
DROP TABLE IF EXISTS [TrackComposers];
DROP TABLE IF EXISTS [TrackPlayTimestamps];
DROP TABLE IF EXISTS [TrackStatses];
DROP TABLE IF EXISTS [Tracks];
DROP TABLE IF EXISTS [AlbumAuthors];
DROP TABLE IF EXISTS [Albums];
DROP TABLE IF EXISTS [Artists];

CREATE TABLE IF NOT EXISTS [Artists] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT
, [Name] TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS [Albums] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT
, [Name] TEXT NOT NULL UNIQUE
, [IsLoved] BIT NOT NULL DEFAULT 0
, [ReleaseDateTimeTicks] INTEGER NULL
, [TracksCount] INTEGER NULL
, [DiscsCount] INTEGER NULL
);

CREATE TABLE IF NOT EXISTS [AlbumAuthors] (
  [AlbumId] INTEGER
, [ArtistId] INTEGER NOT NULL
, [Order] INTEGER NOT NULL DEFAULT 0
, PRIMARY KEY ([AlbumId], [ArtistId])
);

CREATE TABLE IF NOT EXISTS [Tracks] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT
, [AddedDateTimeTicks] INTEGER NOT NULL
, [IsLoved] BIT NOT NULL
, [Location] TEXT NOT NULL UNIQUE
, [DurationTicks] INTEGER NOT NULL
, [SyncDateTimeTicks] INTEGER NOT NULL
, [Title] TEXT NULL
, [ArtistId] INTEGER NULL
, [AlbumId] INTEGER NULL
, [Lyrics] TEXT NULL
, [AlbumTrackNumber] INTEGER NULL
, [AlbumDiscNumber] INTEGER NULL
);

CREATE TABLE IF NOT EXISTS [TrackPerformers] (
  [TrackId] INTEGER
, [ArtistId] INTEGER NOT NULL
, [Order] INTEGER NOT NULL DEFAULT 0
, PRIMARY KEY ([TrackId], [ArtistId])
);

CREATE TABLE IF NOT EXISTS [TrackComposers] (
  [TrackId] INTEGER
, [ArtistId] INTEGER NOT NULL
, [Order] INTEGER NOT NULL DEFAULT 0
, PRIMARY KEY ([TrackId], [ArtistId])
);

CREATE TABLE IF NOT EXISTS [TrackStatses] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT
, [TrackId] INTEGER NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS [TrackPlayTimestamps] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT
, [TrackId] INTEGER NOT NULL UNIQUE
);